language: r
pandoc_version: 2.1.1
before_install:
  - nvm install stable
  - npm install netlify-cli -g
  - cd book
sudo: false
cache:
  packages: true
  directories:
  - book/_bookdown_files
  - $HOME/.npm
addons:
  apt:
    packages:
    - libgsl0-dev
    - libxml2-dev
    - libudunits2-dev

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'
- cp -v favicons/* ../_book_output

deploy:
  provider: script
  script: cd .. && netlify deploy --prod --dir _book_output
  skip_cleanup: true
